# Monte Carlo: Caso 2

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import uniform, triang
pd.set_option('display.precision', 2)
pd.set_option('display.float_format', '{:,.2f}'.format)

# Definición del caso

Caso: Minera Fine Copper

Diego Saba, ingeniero de minas, gerente general de Minera Fine Copper, está considerando la apertura de una nueva mina a tajo abierto de mineral de cobre de las especies bornita y calconita en la localidad de Cotabambas, Apurímac.

El Sr. Saba se ha comunicado con Usted para compartirle el Excel con las evaluaciones efectuadas, los cuales se encuentran disponibles en el blackboard. Para que pueda comprender el Excel a continuación se le explica en que consiste el proyecto. Esta nueva mina estará ubicada sobre 5 mil acres de terreno que serán comprados a inicios del proyecto por US\\$ 15 millones.

El proyecto se sustenta en obtener contratos de compra a futuro de concentrados de cobre; para ello se considera que durante el periodo de explotación el precio del mineral se mantendrá en US\\$ 4,550 la tonelada; es decir, no se prevé que dicho precio se incremente en los próximos años. Se prevé que el volumen total de cobre que puede extraerse (reservas) de la mina equivale a 850 mil toneladas. Los contratos requerirán la entrega de todo este volumen en cantidades anuales iguales de toneladas de cobre durante cada uno de los cuatro años de operación. Para la etapa de operación la empresa deberá además efectuar una serie de inversiones en equipos que ascienden a US\\$ 150 millones. Estas inversiones se efectúan en el periodo cero.

Se prevé que luego de cuatro años de operación el cobre habrá sido totalmente extraído; por lo que la compañía considera que podría vender el equipo al término del periodo de operación en US\\$ 75 millones. Los costos variables ascienden a US\\$ 1,980 la tonelada y los costos fijos a US\\$ 500 millones al año. Considerando que la explotación se realizará a tajo abierto, proceso en el que las capas superiores del suelo sobre una veta se quitan y luego se extrae el mineral expuesto.

Hace algún tiempo, la empresa tan sólo extraía el mineral y dejaba el terreno en una condición inutilizable. Los cambios en las disposiciones que regulan la minería la obligan ahora a reparar el terreno; es decir, cuando los filones se agotan, el terreno debe ser restaurado hasta una condición cercana a su estado original. Así, el terreno se puede usar para otros propósitos.

En tal sentido, Minera Fine Copper será responsable de restituir el terreno a la terminación de las operaciones de minería. La compañía contrata a una empresa externa para restaurar todas sus minas a tajo abierto. Se estima que el costo de restauración será de US\\$ 5 millones, lo que ocurrirá un año después del término del periodo de operación. Después de que el terreno se haya restaurado, se prevé que podrá ser vendido a un valor comercial de US\\$ 20 millones. Esto ocurrirá dos años después del término del periodo de operación. Se está asumiendo que no existe impuesto a la renta ni IGV.

El señor Saba ha efectuado la evaluación desde un punto de vista económico considerando un costo de capital de 12% y le solicita que efectúe las modificaciones que sean necesarias en el Excel a fin de aplicar simulaciones Montecarlo para desarrollar las siguientes evaluaciones.

## Inversión Inicial:

* Inversión en terreno: $\displaystyle\text{US\$ }15\text{ millones}$
* Inversión en equipos: $\displaystyle\text{US\$ }150\text{ millones}$

## Operaciones Anuales:

* Año 0: Inversión inicial.
* Años 1-4:
   * Ingresos por ventas de cobre: $\displaystyle\frac{850,000\text{ toneladas}}{4\text{ años}} = 212,500\frac{\text{ toneladas}}{\text{año}} \times \frac{\text{US\$ }4,550}{\text{tonelada}}$
   * Costos variables: $\displaystyle\frac{212,500\text{ toneladas}}{\text{año}} \times \frac{\text{US\$ }1,980}{\text{tonelada}}$
   * Costos fijos: $\displaystyle\frac{\text{US\$ }500\text{ millones}}{\text{año}}$

## Fin de Operaciones (Año 4):

* Venta de equipos: $\displaystyle\text{US\$ }75\text{ millones}$

## Post-Operaciones:

* Año 5: Costo de restauración: $\displaystyle\text{US\$ }5\text{ millones}$
* Año 6: Venta del terreno restaurado: $\displaystyle\text{US\$ }20\text{ millones}$

In [ ]:
df = pd.DataFrame({
    'Inversión en terreno': [15e6],
    'Inversión en equipos': [150e6],
    'Volumen de cobre / año': [850e3/4],
    'Costos fijos / año': [500e6],
})

df['Ingreso por ventas de cobre / año'] = df['Volumen de cobre / año'] * 4550
df['Costos variables / año'] = df['Volumen de cobre / año'] * 1980

df['Flujo de caja / año'] = df['Ingreso por ventas de cobre / año'] - df['Costos variables / año'] - df['Costos fijos / año']

df['Año 0'] = df['Inversión en terreno'] + df['Inversión en equipos']

df['Año 1'] = df['Flujo de caja / año']
df['Año 2'] = df['Flujo de caja / año']
df['Año 3'] = df['Flujo de caja / año']

df['Venta de equipos'] = 75e6
df['Año 4'] = df['Flujo de caja / año'] + df['Venta de equipos']

df['Año 5: costo de restauración'] = 5e6

df['Año 6: venta del terreno restaurado'] = 20e6

df

,Inversión en terreno,Inversión en equipos,Volumen de cobre / año,Costos fijos / año,Ingreso por ventas de cobre / año,Costos variables / año,Flujo de caja / año,Año 0,Año 1,Año 2,Año 3,Venta de equipos,Año 4,Año 5: costo de restauración,Año 6: venta del terreno restaurado
0,"15,000,000.00","150,000,000.00","212,500.00","500,000,000.00","966,875,000.00","420,750,000.00","46,125,000.00","165,000,000.00","46,125,000.00","46,125,000.00","46,125,000.00","75,000,000.00","121,125,000.00","5,000,000.00","20,000,000.00"

## Cálculo del VAN

In [ ]:
r = 0.12

dv = pd.DataFrame({
    'Año 0': -df['Año 0'],
    'Año 1': df['Año 1'] / (1 + r),
    'Año 2': df['Año 2'] / (1 + r)**2,
    'Año 3': df['Año 3'] / (1 + r)**3,
    'Año 4': df['Año 4'] / (1 + r)**4,
    'Año 5': -df['Año 5: costo de restauración'] / (1 + r)**5,
    'Año 6': df['Año 6: venta del terreno restaurado'] / (1 + r)**6,
})

dv['VAN'] = dv['Año 0'] + dv['Año 1'] + dv['Año 2'] + dv['Año 3'] + dv['Año 4'] + dv['Año 5'] + dv['Año 6']

dv

,Año 0,Año 1,Año 2,Año 3,Año 4,Año 5,Año 6,VAN
0,"-165,000,000.00","41,183,035.71","36,770,567.60","32,830,863.93","76,977,127.25","-2,837,134.28","10,132,622.42","30,057,082.64"

# Evaluaciones

## Evaluación 1

Se requiere: Que mediante el uso del @Risk determine la media y desviación estándar del VAN Económico; la probabilidad que el VAN sea mayor al VAN determinado por el señor Saba; la probabilidad de perder y la máxima perdida sabiendo que:

* Según expertos, se espera que el costo variable se comporte bajo una distribución uniforme con un mínimo de US\\$ 1,930 la tonelada y un máximo de US\\$ 2,030 la tonelada.
* Los expertos también señalan que las inversiones en equipos para la etapa de operación se comportan bajo una distribución triangular con un mínimo US\\$ 140 millones, un máximo US\\$ 155 millones y un valor más probable US\\$ 150 millones.
* Finalmente, se prevé que el volumen total de cobre que podría extraerse de la mina responde a una distribución triangular con un volumen mínimo de 600 mil toneladas, un volumen máximo de 950 mil toneladas y un valor más probable de 850 mil toneladas.

### 1. Definición de Distribuciones
* Costo Variable: distribución uniforme entre $\text{US\$ }1,930$ y $\text{US\$ }2,030$.
* Inversiones en Equipos: distribución triangular con mínimo $\text{US\$ }140\text{ millones}$, máximo $\text{US\$ }155\text{ millones}$, y más probable $\text{US\$ }150\text{ millones}$.
* Volumen de Cobre: Distribución triangular con mínimo $600,000\text{ toneladas}$, máximo $950,000\text{ toneladas}$, y más probable $850,000\text{ toneladas}$.

### 2. Simulación de Montecarlo

Configuración:

* Número de Simulaciones: Por ejemplo, 10,000 iteraciones.
* Variables Aleatorias: Generar valores aleatorios para cada una de las variables mencionadas según sus distribuciones.

### 3. Cálculo del VAN

Para cada iteración:

* Año 0:
    * Inversión en terreno: $\text{US\$ }15\text{ millones}$.
    * Inversión en equipos: Variable según la distribución triangular.
* Años 1-4:
    * Ingresos por cobre: $\displaystyle\frac{\text{Volumen de cobre}}{4} \times \text{US\$ }4,550$.
    * Costos variables: $\displaystyle\frac{\text{Volumen de cobre}}{4} \times \text{Costo variable aleatorio}$.
    * Costos fijos: $\text{US\$ }500\text{ millones}$.
* Año 4:
    * Venta de equipos: $\text{US\$ }75\text{ millones}$.
* Año 5:
    * Costo de restauración: $\text{US\$ }5\text{ millones}$.
* Año 6:
    * Venta del terreno: $\text{US\$ }20\text{ millones}$.
    * Descontar todos los flujos de caja al año 0 usando un costo de capital del $12\%$ para obtener el *VAN*.

In [ ]:
num_iter = 50000

df = pd.DataFrame({
    'Inversión en terreno': np.repeat(15e6, num_iter),
    'Inversión en equipos (Triangular)': np.random.triangular(140e6, 150e6, 155e6, num_iter),
    'Volumen de cobre / año (Triangular)': np.random.triangular(600e3, 850e3, 950e3, num_iter) / 4,
    'Costos fijos / año': np.repeat(500e6, num_iter),
})

df['Ingreso por ventas de cobre / año'] = df['Volumen de cobre / año (Triangular)'] * 4550

df['Costo variable / u (Uniforme)'] = np.random.uniform(1930, 2030, num_iter)
df['Costos variables / año'] = df['Volumen de cobre / año (Triangular)'] * df['Costo variable / u (Uniforme)']

df['Flujo de caja / año'] = df['Ingreso por ventas de cobre / año'] - df['Costos variables / año'] - df['Costos fijos / año']

df['Año 0'] = df['Inversión en terreno'] + df['Inversión en equipos (Triangular)']

df['Año 1'] = df['Flujo de caja / año']
df['Año 2'] = df['Flujo de caja / año']
df['Año 3'] = df['Flujo de caja / año']

df['Venta de equipos'] = 75e6
df['Año 4'] = df['Flujo de caja / año'] + df['Venta de equipos']

df['Año 5: costo de restauración'] = 5e6

df['Año 6: venta del terreno restaurado'] = 20e6

df.head()

,Inversión en terreno,Inversión en equipos (Triangular),Volumen de cobre / año (Triangular),Costos fijos / año,Ingreso por ventas de cobre / año,Costo variable / u (Uniforme),Costos variables / año,Flujo de caja / año,Año 0,Año 1,Año 2,Año 3,Venta de equipos,Año 4,Año 5: costo de restauración,Año 6: venta del terreno restaurado
0,"15,000,000.00","144,308,269.17","200,034.50","500,000,000.00","910,156,975.24","1,960.69","392,206,581.23","17,950,394.01","159,308,269.17","17,950,394.01","17,950,394.01","17,950,394.01","75,000,000.00","92,950,394.01","5,000,000.00","20,000,000.00"
1,"15,000,000.00","149,358,388.24","222,583.54","500,000,000.00","1,012,755,092.20","2,006.82","446,685,985.03","66,069,107.17","164,358,388.24","66,069,107.17","66,069,107.17","66,069,107.17","75,000,000.00","141,069,107.17","5,000,000.00","20,000,000.00"
2,"15,000,000.00","149,342,677.21","181,031.38","500,000,000.00","823,692,780.34","1,953.31","353,610,158.93","-29,917,378.59","164,342,677.21","-29,917,378.59","-29,917,378.59","-29,917,378.59","75,000,000.00","45,082,621.41","5,000,000.00","20,000,000.00"
3,"15,000,000.00","151,786,019.41","168,230.54","500,000,000.00","765,448,979.03","1,944.75","327,166,137.34","-61,717,158.31","166,786,019.41","-61,717,158.31","-61,717,158.31","-61,717,158.31","75,000,000.00","13,282,841.69","5,000,000.00","20,000,000.00"
4,"15,000,000.00","148,518,243.40","219,376.78","500,000,000.00","998,164,336.37","2,011.40","441,254,891.60","56,909,444.77","163,518,243.40","56,909,444.77","56,909,444.77","56,909,444.77","75,000,000.00","131,909,444.77","5,000,000.00","20,000,000.00"

In [ ]:
r = 0.12

dv = pd.DataFrame({
    'Año 0': -df['Año 0'],
    'Año 1': df['Año 1'] / (1 + r),
    'Año 2': df['Año 2'] / (1 + r)**2,
    'Año 3': df['Año 3'] / (1 + r)**3,
    'Año 4': df['Año 4'] / (1 + r)**4,
    'Año 5': -df['Año 5: costo de restauración'] / (1 + r)**5,
    'Año 6': df['Año 6: venta del terreno restaurado'] / (1 + r)**6,
})

dv['VAN'] = dv['Año 0'] + dv['Año 1'] + dv['Año 2'] + dv['Año 3'] + dv['Año 4'] + dv['Año 5'] + dv['Año 6']

dv.head()

,Año 0,Año 1,Año 2,Año 3,Año 4,Año 5,Año 6,VAN
0,"-159,308,269.17","16,027,137.51","14,309,944.20","12,776,735.90","59,071,655.79","-2,837,134.28","10,132,622.42","-49,827,307.63"
1,"-164,358,388.24","58,990,274.26","52,669,887.73","47,026,685.47","89,651,967.91","-2,837,134.28","10,132,622.42","91,275,915.28"
2,"-164,342,677.21","-26,711,945.17","-23,849,951.05","-21,294,599.15","28,650,820.93","-2,837,134.28","10,132,622.42","-200,252,863.50"
3,"-166,786,019.41","-55,104,605.63","-49,200,540.74","-43,929,054.24","8,441,486.03","-2,837,134.28","10,132,622.42","-299,283,245.85"
4,"-163,518,243.40","50,812,004.26","45,367,860.94","40,507,018.70","83,830,836.86","-2,837,134.28","10,132,622.42","64,294,965.50"

In [ ]:
print('media:', dv['VAN'].mean())
print('desviación estándar:', dv['VAN'].std())

media: -66186121.34760643
desviación estándar: 145150628.81224567

In [ ]:
dx = pd.DataFrame({'VAN simulado': dv['VAN']})

dx['> Saba VAN'] = dx['VAN simulado'] > 30_057_082.64
dx['VAN pérdida'] = dx['VAN simulado'] < 0

dx.head()

     VAN simulado  > Saba VAN  VAN pérdida
0  -49,827,307.63       False         True
1   91,275,915.28        True        False
2 -200,252,863.50       False         True
3 -299,283,245.85       False         True
4   64,294,965.50        True        False

In [ ]:
print('Probabilidad que sea > al Saba VAN:', dx['> Saba VAN'].sum() / num_iter)
print('Probabilidad de perder:', dx['VAN pérdida'].sum() / num_iter)
print('Máxima pérdida:', '{:,.2f}'.format(abs(dx['VAN simulado'].min())))

Probabilidad que sea > al Saba VAN: 0.292
Probabilidad de perder: 0.6255
Máxima pérdida: 468,554,775.65

## Evaluación 2

El Excel contiene también la evaluación de una segunda alternativa que consiste en dividir el proyecto en dos etapas. La primera es una Etapa de Exploración y Factibilidad de dos años, en los cuales se invertirá en un estudio de exploración y factibilidad un monto de US\\$ 10 millones cada año. Bajo esta alternativa, en el periodo cero sólo se invertirá en adquirir el terreno.

La Etapa de Explotación considera el efectuar las inversiones señaladas previamente en equipos en el periodo dos que coincide con el término de la Etapa de Exploración y Factibilidad. En cuanto a la etapa de operación, esta iniciaría al término del periodo de exploración y factibilidad.

Se requiere: Que mediante el uso del @Risk determine la media y desviación estándar del VAN Económico; la probabilidad que el VAN sea mayor al VAN determinado por el señor Saba; la probabilidad de perder y la máxima perdida considerando que:

* La Etapa de Explotación iniciara solo sí el estudio de exploración y factibilidad determina que el volumen total del yacimiento que puede extraerse (reservas) es mayor o igual a 850 mil toneladas. Considere nuevamente que el volumen total de cobre que podría determinar dicho estudio responde a una distribución triangular con un volumen mínimo de 600 mil toneladas, un volumen máximo de 950 mil toneladas y un valor más probable de 850 mil toneladas.
* En caso no se verifique el volumen total del yacimiento señalado se cancela el proyecto vendiendo el terreno al término de la etapa de exploración y factibilidad en US\\$ 15 millones. Considere también las distribuciones indicadas en la evaluación I para el costo variable y para las inversiones en equipos para la etapa de operación.

### 1. Etapa de Exploración y Factibilidad (Años 0-1):

* Año 0:
    * Compra de terreno: US\\$ 15 millones.
* Años 1-2:
    * Inversión en estudios: US\\$ 10 millones/año.

### 2. Condición de Viabilidad:

Al final del Año 2: Se simula el volumen de reservas de cobre. Si es ≥ 850,000 toneladas, se procede a la explotación. Si no, se vende el terreno por US\\$ 15 millones.

### 3. Etapa de Explotación (Años 3-6):

* Año 2:
    * Inversión en equipos: Variable según distribución triangular.
* Años 3-6:
    * Ingresos, costos, y flujos de caja como en la primera evaluación, pero con la condición de que solo se ejecuta si las reservas son viables

### 4. Cálculo del VAN

* Variables Aleatorias:
    * Volumen de Reservas: Distribución triangular (600,000 - 950,000 toneladas, más probable 850,000).
    * Costo Variable: Distribución uniforme (US\\$ 1,930 - US\\$ 2,030/tonelada).
    * Inversiones en Equipos: Distribución triangular (US\\$ 140 - US\\$ 155 millones, más probable US\\$ 150 millones).
* Escenario de No Viabilidad:
    * Si el volumen de reservas es < 850,000 toneladas, se vende el terreno al final del Año 2 por US\\$ 15 millones y se termina el proyecto.

### Casos

#### Base

In [ ]:
df = pd.DataFrame({
    'Inversión en terreno': [15e6],
    'Estudio exploración y factibilidad': [10e6],
    'Inversión en equipos': [150e6],
    'Volumen de cobre / año': [850e3/4],
    'Costos fijos / año': [500e6],
})

df['Ingreso por ventas de cobre / año'] = df['Volumen de cobre / año'] * 4550
df['Costos variables / año'] = df['Volumen de cobre / año'] * 1980

df['Flujo de caja / año'] = df['Ingreso por ventas de cobre / año'] - df['Costos variables / año'] - df['Costos fijos / año']

df['Año 0'] = df['Inversión en terreno']
df['Año 1'] = df['Estudio exploración y factibilidad']
df['Año 2'] = df['Estudio exploración y factibilidad'] + df['Inversión en equipos']
df['Año 3'] = df['Flujo de caja / año']
df['Año 4'] = df['Flujo de caja / año']
df['Año 5'] = df['Flujo de caja / año']

df['Venta de equipos'] = 75e6
df['Año 6'] = df['Flujo de caja / año'] + df['Venta de equipos']


df['Año 7: costo de restauración'] = 5e6
df['Año 8: venta del terreno restaurado'] = 20e6

df

,Inversión en terreno,Estudio exploración y factibilidad,Inversión en equipos,Volumen de cobre / año,Costos fijos / año,Ingreso por ventas de cobre / año,Costos variables / año,Flujo de caja / año,Año 0,Año 1,Año 2,Año 3,Año 4,Año 5,Venta de equipos,Año 6,Año 7: costo de restauración,Año 8: venta del terreno restaurado
0,"15,000,000.00","10,000,000.00","150,000,000.00","212,500.00","500,000,000.00","966,875,000.00","420,750,000.00","46,125,000.00","15,000,000.00","10,000,000.00","160,000,000.00","46,125,000.00","46,125,000.00","46,125,000.00","75,000,000.00","121,125,000.00","5,000,000.00","20,000,000.00"

In [ ]:
r = 0.12

dv = pd.DataFrame({
    'Año 0': -df['Año 0'],
    'Año 1': -df['Año 1'] / (1 + r),
    'Año 2': -df['Año 2'] / (1 + r)**2,
    'Año 3': df['Año 3'] / (1 + r)**3,
    'Año 4': df['Año 4'] / (1 + r)**4,
    'Año 5': df['Año 5'] / (1 + r)**5,
    'Año 6': df['Año 6'] / (1 + r)**6,
    'Año 7': -df['Año 7: costo de restauración'] / (1 + r)**7,
    'Año 8': df['Año 8: venta del terreno restaurado'] / (1 + r)**8,
})

dv['VAN'] = dv['Año 0'] + dv['Año 1'] + dv['Año 2'] + dv['Año 3'] + dv['Año 4'] + dv['Año 5'] + dv['Año 6'] + dv['Año 7'] + dv['Año 8']

dv

,Año 0,Año 1,Año 2,Año 3,Año 4,Año 5,Año 6,Año 7,Año 8,VAN
0,"-15,000,000.00","-8,928,571.43","-127,551,020.41","32,830,863.93","29,313,271.37","26,172,563.72","61,365,694.55","-2,261,746.08","8,077,664.56","4,018,720.22"

#### Simulación

In [ ]:
num_iter = 50000

df = pd.DataFrame({
    'Inversión en terreno': np.repeat(15e6, num_iter),
    'Estudio exploración y factibilidad': np.repeat(10e6, num_iter),
    'Inversión en equipos (Triangular)': np.random.triangular(140e6, 150e6, 155e6, num_iter),
    'Volumen de cobre total (Triangular)': np.random.triangular(600e3, 850e3, 950e3, num_iter),
})

df['Volumen de cobre total ≥ 850 000'] = df['Volumen de cobre total (Triangular)'] >= 850e3

df['Volumen de cobre / año (Triangular)'] = df['Volumen de cobre total (Triangular)']  / 4
df['Costos fijos / año'] = 500e6

df['Ingreso por ventas de cobre / año'] = df['Volumen de cobre / año (Triangular)'] * 4550

df['Costo variable / u (Uniforme)'] = np.random.uniform(1930, 2030, num_iter)
df['Costos variables / año'] = df['Volumen de cobre / año (Triangular)'] * df['Costo variable / u (Uniforme)']

df['Flujo de caja / año'] = (df['Ingreso por ventas de cobre / año'] - df['Costos variables / año'] - df['Costos fijos / año']) * df['Volumen de cobre total ≥ 850 000']

df['Año 0'] = df['Inversión en terreno']
df['Año 1'] = df['Estudio exploración y factibilidad']
df['Año 2'] = -df['Estudio exploración y factibilidad'] + df['Inversión en equipos (Triangular)'] * df['Volumen de cobre total ≥ 850 000'] + (15e6 * ~df['Volumen de cobre total ≥ 850 000'])
df['Año 3'] = df['Flujo de caja / año']
df['Año 4'] = df['Flujo de caja / año']
df['Año 5'] = df['Flujo de caja / año']

df['Venta de equipos'] = 75e6
df['Año 6'] = df['Flujo de caja / año'] + df['Venta de equipos'] * df['Volumen de cobre total ≥ 850 000']


df['Año 7: costo de restauración'] = 5e6  * df['Volumen de cobre total ≥ 850 000']
df['Año 8: venta del terreno restaurado'] = 20e6  * df['Volumen de cobre total ≥ 850 000']

df.head()

,Inversión en terreno,Estudio exploración y factibilidad,Inversión en equipos (Triangular),Volumen de cobre total (Triangular),Volumen de cobre total ≥ 850 000,Volumen de cobre / año (Triangular),Costos fijos / año,Ingreso por ventas de cobre / año,Costo variable / u (Uniforme),Costos variables / año,...,Año 0,Año 1,Año 2,Año 3,Año 4,Año 5,Venta de equipos,Año 6,Año 7: costo de restauración,Año 8: venta del terreno restaurado
0,"15,000,000.00","10,000,000.00","143,370,578.03","791,240.51",False,"197,810.13","500,000,000.00","900,036,077.63","1,971.29","389,941,827.57",...,"15,000,000.00","10,000,000.00","5,000,000.00",0.00,0.00,0.00,"75,000,000.00",0.00,0.00,0.00
1,"15,000,000.00","10,000,000.00","143,228,021.65","717,097.59",False,"179,274.40","500,000,000.00","815,698,503.26","2,004.07","359,279,266.23",...,"15,000,000.00","10,000,000.00","5,000,000.00",-0.00,-0.00,-0.00,"75,000,000.00",0.00,0.00,0.00
2,"15,000,000.00","10,000,000.00","151,561,729.86","715,565.46",False,"178,891.36","500,000,000.00","813,955,708.54","1,993.48","356,615,713.65",...,"15,000,000.00","10,000,000.00","5,000,000.00",-0.00,-0.00,-0.00,"75,000,000.00",0.00,0.00,0.00
3,"15,000,000.00","10,000,000.00","145,101,472.55","854,963.94",True,"213,740.99","500,000,000.00","972,521,485.22","1,984.62","424,195,364.12",...,"15,000,000.00","10,000,000.00","135,101,472.55","48,326,121.09","48,326,121.09","48,326,121.09","75,000,000.00","123,326,121.09","5,000,000.00","20,000,000.00"
4,"15,000,000.00","10,000,000.00","150,488,050.28","657,475.60",False,"164,368.90","500,000,000.00","747,878,497.01","1,947.10","320,043,059.49",...,"15,000,000.00","10,000,000.00","5,000,000.00",-0.00,-0.00,-0.00,"75,000,000.00",0.00,0.00,0.00

In [ ]:
r = 0.12

dv = pd.DataFrame({
    'Año 0': -df['Año 0'],
    'Año 1': -df['Año 1'] / (1 + r),
    'Año 2': df['Año 2'] / (1 + r)**2,
    'Año 3': df['Año 3'] / (1 + r)**3,
    'Año 4': df['Año 4'] / (1 + r)**4,
    'Año 5': df['Año 5'] / (1 + r)**5,
    'Año 6': df['Año 6'] / (1 + r)**6,
    'Año 7': -df['Año 7: costo de restauración'] / (1 + r)**7,
    'Año 8': df['Año 8: venta del terreno restaurado'] / (1 + r)**8,
})

dv['VAN'] = dv['Año 0'] + dv['Año 1'] + dv['Año 2'] + dv['Año 3'] + dv['Año 4'] + dv['Año 5'] + dv['Año 6'] + dv['Año 7'] + dv['Año 8']

dv.head()

,Año 0,Año 1,Año 2,Año 3,Año 4,Año 5,Año 6,Año 7,Año 8,VAN
0,"-15,000,000.00","-8,928,571.43","3,985,969.39",0.00,0.00,0.00,0.00,-0.00,0.00,"-19,942,602.04"
1,"-15,000,000.00","-8,928,571.43","3,985,969.39",-0.00,-0.00,-0.00,0.00,-0.00,0.00,"-19,942,602.04"
2,"-15,000,000.00","-8,928,571.43","3,985,969.39",-0.00,-0.00,-0.00,0.00,-0.00,0.00,"-19,942,602.04"
3,"-15,000,000.00","-8,928,571.43","107,702,066.77","34,397,578.45","30,712,123.61","27,421,538.94","62,480,851.00","-2,261,746.08","8,077,664.56","244,601,505.83"
4,"-15,000,000.00","-8,928,571.43","3,985,969.39",-0.00,-0.00,-0.00,0.00,-0.00,0.00,"-19,942,602.04"

In [ ]:
print('media:', dv['VAN'].mean())
print('desviación estándar:', dv['VAN'].std())

media: 69399880.11812885
desviación estándar: 143322220.36018473

In [ ]:
dx = pd.DataFrame({'VAN simulado': dv['VAN']})

dx['> Saba VAN'] = dx['VAN simulado'] > 30_057_082.64
dx['VAN pérdida'] = dx['VAN simulado'] < 0

dx.head()

    VAN simulado  > Saba VAN  VAN pérdida
0 -19,942,602.04       False         True
1 -19,942,602.04       False         True
2 -19,942,602.04       False         True
3 244,601,505.83        True        False
4 -19,942,602.04       False         True

In [ ]:
print('Probabilidad que sea > al Saba VAN:', dx['> Saba VAN'].sum() / num_iter)
print('Probabilidad de perder:', dx['VAN pérdida'].sum() / num_iter)
print('Máxima pérdida:', '{:,.2f}'.format(abs(dx['VAN simulado'].min())))

Probabilidad que sea > al Saba VAN: 0.28444
Probabilidad de perder: 0.71556
Máxima pérdida: 19,942,602.04

## Evaluación 3

Finalmente, se requiere que recomiende si se debe ejecutar el proyecto en una sola etapa o en dos etapas (Etapa de Exploración y Factibilidad y Etapa de Explotación). Al respecto, en el Excel que se comparte podrá observar que el VAN de hacer el proyecto considerando la etapa de exploración y factibilidad genera un menor VAN Económico; por lo que el Sr. Saba estaría tentado a descartar esta alternativa, salvo que usted recomiende adecuadamente lo contrario.